// TODO: выпилить когда будет апи
import { ICategory } from '@/types';

export const categories: ICategory[] = [
  {
    id: 1,
    slug: 'it_technology',
    title: 'ИТ Технологии',
    description: 'просто описание к категории ит технологии',
    image: 'notebook.webp',
    alt: 'computer',
  },
  {
    id: 2,
    slug: 'accountant',
    title: 'Бух. учет',
    description: 'просто описание к категории бух учет',
    image: 'paperwork.webp',
    alt: 'paperwork',
  },
  {
    id: 3,
    slug: 'language',
    title: 'Иностранные языки',
    description: 'просто описание к категории иностранные языки',
    image: 'language.webp',
    alt: 'language',
  },
  {
    id: 4,
    slug: 'accountant',
    title: 'Бух. учет',
    description: 'просто описание к категории бух учет',
    image: 'paperwork.webp',
    alt: 'paperwork',
  },
  {
    id: 5,
    slug: 'it_technology',
    title: 'ИТ Технологии',
    description: 'просто описание к категории ит технологии',
    image: 'notebook.webp',
    alt: 'computer',
  },
  {
    id: 6,
    slug: 'language',
    title: 'Иностранные языки',
    description: 'просто описание к категории иностранные языки',
    image: 'language.webp',
    alt: 'language',
  },
  {
    id: 7,
    slug: 'language',
    title: 'Иностранные языки',
    description: 'просто описание к категории иностранные языки',
    image: 'language.webp',
    alt: 'language',
  },
  {
    id: 8,
    slug: 'language',
    title: 'Иностранные языки',
    description: 'просто описание к категории иностранные языки',
    image: 'language.webp',
    alt: 'language',
  },
  {
    id: 9,
    slug: 'language',
    title: 'Иностранные языки',
    description: 'просто описание к категории иностранные языки',
    image: 'language.webp',
    alt: 'language',
  },
  {
    id: 10,
    slug: 'language',
    title: 'Иностранные языки',
    description: 'просто описание к категории иностранные языки',
    image: 'language.webp',
    alt: 'language',
  },
];
